### ISSUE TITLE
Non-ASCII characters in extension results cause print statement to fail

### ISSUE THREAD

**Issue by opragel** [christophercollins/casper_extension_attributes#1]
Thanks for the script, it's been very helpful already.

When I first tried running the script I was getting this error:

```
$ python chromeExtensions.py3 
Traceback (most recent call last):
  File "chromeExtensions.py3", line 60, in <module>
    print "<result>{}</result>".format(', '.join(sorted(list(set(installed_extensions)))))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2080' in position 816: ordinal not in range(128)
```

I was able to get the print to function to finish by converting the string to UTF-8. 

```
print "<result>{}</result>".format(', '.join(sorted(list(set(installed_extensions)))).encode('utf-8'))
```

Not exactly sure where it came from, but it seems like I'm seeing a Unicode U+2091 subscript character after the last Chrome extension name? Appears like: `uBlock[U+2091]</result>` for me.

**Comment by christophercollins** [comment]
Thanks Owen. I merged it. Glad you got some use out of the script!
